CREATE SCHEMA IF NOT EXISTS control;
GRANT USAGE ON SCHEMA control TO {db_user};
GRANT {db_user} TO CURRENT_USER;
ALTER SCHEMA control OWNER TO {db_user};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA control TO {db_user};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA control TO {db_user};

ALTER DEFAULT PRIVILEGES IN SCHEMA control 
  GRANT USAGE, SELECT ON SEQUENCES TO {db_user};